import nextPwa from 'next-pwa';

/**
 * PWA configuration — turns the dashboard into an installable web app so
 * a plant owner can "Add to Home Screen" on their phone and the
 * experience feels app-like (full-screen, no browser chrome, offline
 * shell). Service worker is generated by next-pwa (Workbox underneath).
 *
 * Why we went PWA instead of finishing the Expo `mobile-admin` app:
 *   - One codebase (this dashboard) instead of maintaining a parallel
 *     React Native screen for every dashboard feature.
 *   - All the heavy admin work (accounting, reports, audit logs,
 *     team management) needs tables + multi-column layouts that don't
 *     translate well to a 5-inch phone — same code, just responsive.
 *   - Distribution: no Play Store / TestFlight gatekeeping for v0; we
 *     can ship a fix in 30 seconds via the regular Next.js deploy.
 *   - Iraq market is ~90%+ Android-Chrome, where web push + PWA install
 *     work reliably. iOS 16.4+ Safari also supports both.
 */
const withPWA = nextPwa({
  dest: 'public',
  register: true,
  skipWaiting: true,
  // Dev mode without a service worker — old SW caches reloading old
  // assets while we iterate is worse than no SW at all.
  disable: process.env.NODE_ENV === 'development',
  // Don't precache the /api proxy — those responses are user-scoped and
  // should never be served from a stale SW cache. Everything else
  // (static HTML, JS, CSS, fonts, icons) precaches normally.
  buildExcludes: [/middleware-manifest\.json$/, /api\/.*$/],
});

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  experimental: { typedRoutes: true },
  env: {
    NEXT_PUBLIC_API_URL: process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3000/api/v1',
  },
};

export default withPWA(nextConfig);
